services:
  django-celery-worker:
    build: .
    volumes:
      - ./celery_django_sample:/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ broker port
      - "15672:15672"  # RabbitMQ management UI port
